site_name: GitHub Portfolio System
site_description: A production-grade framework for automating and maintaining professional GitHub portfolios.
site_author: Adith Shajee
repo_url: https://github.com/Adithshajee/github-portfolio-system

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
    - scheme: slate
      primary: blue
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Setup Guide: setup.md
  - CI/CD Workflows: ci-cd.md
  - Deployment Guide: deployment.md
  - Roadmap: roadmap.md

extra_css:
  - assets/custom.css

