name: Deploy Documentation Site

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements.txt"
      - ".github/workflows/deploy_docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy MkDocs to GitHub Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mike deploy --deploy-prefix dist -p -u latest || mkdocs gh-deploy --force
